name: NoFlight
version: '0.1'
main: me.deadybbb.noflight.NoFlight
api-version: '1.20'
authors: [ Ybbb ]
commands:
  noflight:
    description: Выдаёт эффект NoFlight на игрока
    usage: /<command> <player>