name: NoFlight
version: '0.1'
main: me.deadybbb.noflight.NoFlight
api-version: '1.20'
authors: [ Ybbb ]
commands:
  noflight:
    description: Applies the NoFlight effect to a player
    usage: /<command> <player> <seconds>
    permission: minecraft.command.op