name: NoFlight
version: '0.1'
main: me.deadybbb.noflight.NoFlight
api-version: '1.20'
authors: [ Ybbb ]
commands:
  noflight:
    description: Gives effect NoFlight on the player
    usage: /<command> <player>